### ISSUE TITLE
"Authorization Demo App" has not been white-listed by FHIR Play Millennium for use.

### ISSUE THREAD

**Issue by 10101010101010001** [cerner/code-learning-lab#15]
Thank you for everyone's hard work! 

I'm having an issue on step two.  Could someone take a look?

![1](https://user-images.githubusercontent.com/67249583/101816660-e98aaa00-3ae6-11eb-88f8-0b26abc0cf9f.png)

![2](https://user-images.githubusercontent.com/67249583/101816690-f1e2e500-3ae6-11eb-8ca6-68c096993e19.png)

FHIR Play Millennium has not enabled "Authorization Demo App" for accessing healthcare data yet. If you require further assistance, please contact support.
If possible, please bookmark this page or take a screen shot of it to expedite the technical support process. For assistance, contact support via:
E-mail:sample@provider-example.com
Phone:123-456-7890
Information to provide to Technical Support
Correlation ID:ab9ff618-f3bd-4dc3-878d-022d9f2efd97
Information to provide to Authorization Demo App
"Authorization Demo App" has not been white-listed by FHIR Play Millennium for use.

**Comment by MaxPhilips** [comment]
hi @10101010101010001 - thanks for the report!

we need to update the SMART Authorization lab in this case. Cerner has changed our public sandbox URLs and we have not updated that document. we'll get this addressed

Max (Cerner)

**Comment by MaxPhilips** [comment]
@10101010101010001 updates have been made! please let us know if you run into any other issues.
